/**
 * dungeonSeeds.ts — 20개 던전 시드 데이터 (P5-03)
 *
 * 지역당 3~4개, 난이도 3단계 (normal / hard / nightmare)
 * 웨이브 구성: 일반 3~5웨이브 + 보스 1웨이브
 */
import { prisma } from '../db';

// ─── 던전 시드 ──────────────────────────────────────────────────

interface DungeonSeed {
  code: string;
  name: string;
  description: string;
  zoneCode: string;     // zoneSeeds의 zone code 참조
  difficulty: string;
  requiredLevel: number;
  maxPlayers: number;
  waves: { wave: number; monsters: { monsterId: string; count: number }[]; isBoss: boolean }[];
  rewards: { gold: number; exp: number; items: { itemId: string; rate: number; count: number }[] };
  timeLimit: number;
  entryCount: number;
}

const DUNGEON_SEEDS: DungeonSeed[] = [
  // ═══ 아르겐티움 (Lv.1-15) ═══════════════════════════════════
  {
    code: 'dg_argentium_sewer_n',
    name: '하수도 미궁 (일반)',
    description: '아르겐티움 지하 하수도에 서식하는 변이 쥐떼와 슬라임 보스를 처치하라.',
    zoneCode: 'argentium_sewer',
    difficulty: 'normal',
    requiredLevel: 5,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_sewer_rat', count: 5 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_sewer_rat', count: 4 }, { monsterId: 'mob_toxic_slime', count: 2 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_toxic_slime', count: 6 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'boss_sewer_king', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 500, exp: 1200, items: [{ itemId: 'item_sewer_key', rate: 0.3, count: 1 }] },
    timeLimit: 600,
    entryCount: 3,
  },
  {
    code: 'dg_argentium_sewer_h',
    name: '하수도 미궁 (하드)',
    description: '강화된 변이체가 출몰하는 하수도. 독 면역 장비 권장.',
    zoneCode: 'argentium_sewer',
    difficulty: 'hard',
    requiredLevel: 10,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_sewer_rat', count: 8 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_toxic_slime', count: 6 }, { monsterId: 'mob_plague_rat', count: 3 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_plague_rat', count: 5 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'mob_toxic_slime', count: 4 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'boss_sewer_king', count: 1 }, { monsterId: 'mob_toxic_slime', count: 2 }], isBoss: true },
    ],
    rewards: { gold: 1200, exp: 3000, items: [{ itemId: 'item_sewer_key', rate: 0.5, count: 1 }, { itemId: 'item_poison_ring', rate: 0.15, count: 1 }] },
    timeLimit: 900,
    entryCount: 2,
  },
  {
    code: 'dg_argentium_tower_n',
    name: '황금탑 외곽 시련 (일반)',
    description: '황금탑 외곽을 지키는 골렘과 기사단 잔재를 돌파하라.',
    zoneCode: 'argentium_tower',
    difficulty: 'normal',
    requiredLevel: 12,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_tower_guard', count: 4 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_tower_guard', count: 3 }, { monsterId: 'mob_stone_golem', count: 2 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_stone_golem', count: 4 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'boss_golden_sentinel', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 800, exp: 2000, items: [{ itemId: 'item_golden_shard', rate: 0.25, count: 1 }] },
    timeLimit: 600,
    entryCount: 3,
  },

  // ═══ 실반헤임 (Lv.10-30) ═════════════════════════════════════
  {
    code: 'dg_silvanhome_mist_n',
    name: '안개 습지 정화 (일반)',
    description: '안개 습지에 퍼진 부패 정령을 소탕하고 수호석을 회수하라.',
    zoneCode: 'silvanhome_mist',
    difficulty: 'normal',
    requiredLevel: 15,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_corrupt_sprite', count: 6 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_swamp_treant', count: 3 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_corrupt_sprite', count: 4 }, { monsterId: 'mob_swamp_treant', count: 2 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'boss_mist_wraith', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 1000, exp: 2500, items: [{ itemId: 'item_guardian_stone', rate: 0.2, count: 1 }] },
    timeLimit: 600,
    entryCount: 3,
  },
  {
    code: 'dg_silvanhome_crystal_n',
    name: '수정 동굴 탐사 (일반)',
    description: '에테르 결정이 자라는 동굴 깊은 곳의 결정 골렘을 격파하라.',
    zoneCode: 'silvanhome_crystal',
    difficulty: 'normal',
    requiredLevel: 20,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_crystal_bat', count: 8 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_crystal_spider', count: 5 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_crystal_golem', count: 3 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'boss_crystal_titan', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 1500, exp: 3500, items: [{ itemId: 'item_aether_crystal', rate: 0.3, count: 2 }] },
    timeLimit: 600,
    entryCount: 3,
  },
  {
    code: 'dg_silvanhome_crystal_h',
    name: '수정 동굴 탐사 (하드)',
    description: '결정 에너지가 폭주한 동굴. 타이탄이 2차 형태로 변이한다.',
    zoneCode: 'silvanhome_crystal',
    difficulty: 'hard',
    requiredLevel: 25,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_crystal_spider', count: 6 }, { monsterId: 'mob_crystal_bat', count: 4 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_crystal_golem', count: 5 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_crystal_golem', count: 3 }, { monsterId: 'mob_crystal_spider', count: 4 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'boss_crystal_titan', count: 1 }, { monsterId: 'mob_crystal_golem', count: 2 }], isBoss: true },
    ],
    rewards: { gold: 3000, exp: 7000, items: [{ itemId: 'item_aether_crystal', rate: 0.5, count: 3 }, { itemId: 'item_crystal_heart', rate: 0.1, count: 1 }] },
    timeLimit: 900,
    entryCount: 2,
  },

  // ═══ 에레보스 (Lv.25-45) ═════════════════════════════════════
  {
    code: 'dg_erebos_cathedral_n',
    name: '망각의 성당 (일반)',
    description: '잊혀진 성당에 깃든 망령들을 퇴마하고 성물을 회수하라.',
    zoneCode: 'erebos_cathedral',
    difficulty: 'normal',
    requiredLevel: 30,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_wraith', count: 6 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_wraith', count: 4 }, { monsterId: 'mob_banshee', count: 2 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_banshee', count: 5 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'boss_forgotten_bishop', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 2000, exp: 5000, items: [{ itemId: 'item_holy_relic', rate: 0.2, count: 1 }] },
    timeLimit: 600,
    entryCount: 3,
  },
  {
    code: 'dg_erebos_catacomb_n',
    name: '지하 카타콤 (일반)',
    description: '카타콤 최심부에서 깨어난 리치를 처치하라.',
    zoneCode: 'erebos_catacomb',
    difficulty: 'normal',
    requiredLevel: 35,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_skeleton', count: 8 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_skeleton', count: 4 }, { monsterId: 'mob_bone_knight', count: 3 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_bone_knight', count: 4 }, { monsterId: 'mob_necromancer', count: 2 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'mob_necromancer', count: 3 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'boss_catacomb_lich', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 2500, exp: 6000, items: [{ itemId: 'item_lich_phylactery', rate: 0.15, count: 1 }] },
    timeLimit: 720,
    entryCount: 3,
  },
  {
    code: 'dg_erebos_catacomb_nm',
    name: '지하 카타콤 (나이트메어)',
    description: '리치가 완전체로 부활했다. 4인 파티 필수, 암속성 저항 권장.',
    zoneCode: 'erebos_catacomb',
    difficulty: 'nightmare',
    requiredLevel: 42,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_bone_knight', count: 8 }, { monsterId: 'mob_necromancer', count: 4 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_necromancer', count: 6 }, { monsterId: 'mob_shadow_wraith', count: 3 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_shadow_wraith', count: 6 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'mob_bone_knight', count: 4 }, { monsterId: 'mob_shadow_wraith', count: 4 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'boss_catacomb_lich', count: 1 }, { monsterId: 'mob_necromancer', count: 3 }], isBoss: true },
    ],
    rewards: { gold: 6000, exp: 15000, items: [{ itemId: 'item_lich_phylactery', rate: 0.4, count: 1 }, { itemId: 'item_dark_essence', rate: 0.2, count: 2 }] },
    timeLimit: 1200,
    entryCount: 1,
  },

  // ═══ 솔라리스 사막 (Lv.35-55) ════════════════════════════════
  {
    code: 'dg_solaris_mine_n',
    name: '에테르 광산 (일반)',
    description: '에테르 광맥을 둘러싼 광산 벌레와 보스 드릴웜을 처치하라.',
    zoneCode: 'solaris_mine',
    difficulty: 'normal',
    requiredLevel: 40,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_mine_beetle', count: 6 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_mine_beetle', count: 4 }, { monsterId: 'mob_sand_wyrm', count: 2 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_sand_wyrm', count: 5 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'boss_drillworm', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 3000, exp: 7500, items: [{ itemId: 'item_aether_ore', rate: 0.35, count: 3 }] },
    timeLimit: 600,
    entryCount: 3,
  },
  {
    code: 'dg_solaris_temple_n',
    name: '고대 사원 (일반)',
    description: '사막 깊은 곳의 고대 사원에 봉인된 태양신의 화신과 맞서라.',
    zoneCode: 'solaris_temple',
    difficulty: 'normal',
    requiredLevel: 45,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_sand_elemental', count: 5 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_sand_elemental', count: 3 }, { monsterId: 'mob_temple_guardian', count: 3 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_temple_guardian', count: 5 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'boss_sun_avatar', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 3500, exp: 9000, items: [{ itemId: 'item_sun_fragment', rate: 0.2, count: 1 }] },
    timeLimit: 720,
    entryCount: 3,
  },
  {
    code: 'dg_solaris_temple_h',
    name: '고대 사원 (하드)',
    description: '태양신의 진정한 힘이 깨어났다. 화속성 저항 필수.',
    zoneCode: 'solaris_temple',
    difficulty: 'hard',
    requiredLevel: 50,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_temple_guardian', count: 6 }, { monsterId: 'mob_fire_spirit', count: 3 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_fire_spirit', count: 6 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_temple_guardian', count: 4 }, { monsterId: 'mob_fire_spirit', count: 4 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'boss_sun_avatar', count: 1 }, { monsterId: 'mob_fire_spirit', count: 2 }], isBoss: true },
    ],
    rewards: { gold: 7000, exp: 18000, items: [{ itemId: 'item_sun_fragment', rate: 0.4, count: 2 }, { itemId: 'item_inferno_core', rate: 0.1, count: 1 }] },
    timeLimit: 900,
    entryCount: 2,
  },

  // ═══ 북방 영원빙원 (Lv.50-70) ════════════════════════════════
  {
    code: 'dg_northland_cave_n',
    name: '얼음 동굴 (일반)',
    description: '영원빙원의 얼음 동굴 깊이 서식하는 프로스트 드레이크를 토벌하라.',
    zoneCode: 'northland_cave',
    difficulty: 'normal',
    requiredLevel: 55,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_ice_wolf', count: 6 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_ice_wolf', count: 3 }, { monsterId: 'mob_frost_golem', count: 3 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_frost_golem', count: 5 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'boss_frost_drake', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 4000, exp: 12000, items: [{ itemId: 'item_frost_scale', rate: 0.3, count: 2 }] },
    timeLimit: 720,
    entryCount: 3,
  },
  {
    code: 'dg_northland_peak_n',
    name: '결정 봉우리 (일반)',
    description: '에테르 빙정이 결정화된 봉우리 정상의 크리스탈 와이번을 격파하라.',
    zoneCode: 'northland_peak',
    difficulty: 'normal',
    requiredLevel: 60,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_frost_harpy', count: 5 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_frost_harpy', count: 3 }, { monsterId: 'mob_ice_elemental', count: 3 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_ice_elemental', count: 6 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'boss_crystal_wyvern', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 5000, exp: 15000, items: [{ itemId: 'item_wyvern_crest', rate: 0.2, count: 1 }] },
    timeLimit: 720,
    entryCount: 3,
  },
  {
    code: 'dg_northland_peak_nm',
    name: '결정 봉우리 (나이트메어)',
    description: '빙정 에너지가 폭주한 봉우리. 와이번이 빙룡으로 진화한다.',
    zoneCode: 'northland_peak',
    difficulty: 'nightmare',
    requiredLevel: 68,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_ice_elemental', count: 8 }, { monsterId: 'mob_frost_harpy', count: 4 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_frost_golem', count: 6 }, { monsterId: 'mob_ice_elemental', count: 4 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_frost_golem', count: 5 }, { monsterId: 'mob_frost_harpy', count: 5 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'mob_ice_elemental', count: 6 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'boss_crystal_wyvern', count: 1 }, { monsterId: 'mob_frost_golem', count: 3 }], isBoss: true },
    ],
    rewards: { gold: 12000, exp: 35000, items: [{ itemId: 'item_wyvern_crest', rate: 0.5, count: 2 }, { itemId: 'item_ice_dragon_core', rate: 0.08, count: 1 }] },
    timeLimit: 1200,
    entryCount: 1,
  },

  // ═══ 브리탈리아 자유항 (Lv.15-40) ════════════════════════════
  {
    code: 'dg_britallia_pirate_n',
    name: '해적 소굴 (일반)',
    description: '브리탈리아 해안 동굴의 해적단을 소탕하라.',
    zoneCode: 'britallia_pirate',
    difficulty: 'normal',
    requiredLevel: 20,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_pirate_thug', count: 6 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_pirate_thug', count: 3 }, { monsterId: 'mob_pirate_gunner', count: 3 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_pirate_gunner', count: 5 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'boss_pirate_captain', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 1200, exp: 3000, items: [{ itemId: 'item_pirate_map', rate: 0.25, count: 1 }] },
    timeLimit: 600,
    entryCount: 3,
  },
  {
    code: 'dg_britallia_arena_n',
    name: '지하 투기장 (일반)',
    description: '자유항 지하의 불법 투기장에서 챔피언을 꺾어라.',
    zoneCode: 'britallia_arena',
    difficulty: 'normal',
    requiredLevel: 30,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_arena_brawler', count: 4 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_arena_brawler', count: 3 }, { monsterId: 'mob_arena_mage', count: 2 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_arena_mage', count: 4 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'boss_arena_champion', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 2000, exp: 5500, items: [{ itemId: 'item_champion_belt', rate: 0.15, count: 1 }] },
    timeLimit: 600,
    entryCount: 3,
  },
  {
    code: 'dg_britallia_arena_h',
    name: '지하 투기장 (하드)',
    description: '챔피언이 금지된 에테르 강화를 사용한다. 즉사 기믹 주의.',
    zoneCode: 'britallia_arena',
    difficulty: 'hard',
    requiredLevel: 38,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_arena_brawler', count: 5 }, { monsterId: 'mob_arena_mage', count: 3 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_arena_mage', count: 6 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_arena_brawler', count: 4 }, { monsterId: 'mob_arena_assassin', count: 3 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'mob_arena_assassin', count: 4 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'boss_arena_champion', count: 1 }, { monsterId: 'mob_arena_assassin', count: 2 }], isBoss: true },
    ],
    rewards: { gold: 4500, exp: 12000, items: [{ itemId: 'item_champion_belt', rate: 0.3, count: 1 }, { itemId: 'item_arena_trophy', rate: 0.1, count: 1 }] },
    timeLimit: 900,
    entryCount: 2,
  },

  // ═══ 망각의 고원 (Lv.70-80) ══════════════════════════════════
  {
    code: 'dg_oblivion_rift_n',
    name: '시간 균열 (일반)',
    description: '망각의 고원에 열린 시간 균열에서 쏟아지는 시공 왜곡체를 막아라.',
    zoneCode: 'oblivion_plateau',
    difficulty: 'normal',
    requiredLevel: 72,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_time_phantom', count: 5 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_time_phantom', count: 3 }, { monsterId: 'mob_chrono_beast', count: 3 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_chrono_beast', count: 5 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'mob_void_sentinel', count: 4 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'boss_rift_guardian', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 8000, exp: 25000, items: [{ itemId: 'item_time_shard', rate: 0.3, count: 2 }] },
    timeLimit: 900,
    entryCount: 2,
  },
  {
    code: 'dg_oblivion_rift_nm',
    name: '시간 균열 (나이트메어)',
    description: '균열이 완전히 열렸다. 시공의 수호자가 최종 형태로 각성한다.',
    zoneCode: 'oblivion_plateau',
    difficulty: 'nightmare',
    requiredLevel: 78,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_chrono_beast', count: 8 }, { monsterId: 'mob_void_sentinel', count: 4 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_void_sentinel', count: 6 }, { monsterId: 'mob_time_phantom', count: 4 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_void_sentinel', count: 5 }, { monsterId: 'mob_chrono_beast', count: 5 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'mob_time_phantom', count: 6 }, { monsterId: 'mob_void_sentinel', count: 4 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'boss_rift_guardian', count: 1 }, { monsterId: 'mob_void_sentinel', count: 3 }], isBoss: true },
    ],
    rewards: { gold: 20000, exp: 60000, items: [{ itemId: 'item_time_shard', rate: 0.6, count: 3 }, { itemId: 'item_chrono_core', rate: 0.05, count: 1 }] },
    timeLimit: 1500,
    entryCount: 1,
  },
  // ═══ 무한 안개해 (Lv.70-90) [P8-13] ═════════════════════════════
  // ── 1. 기억의 등대 (3난이도) ──
  {
    code: 'dg_mistsea_lighthouse_n',
    name: '기억의 등대 (일반)',
    description: '봉인자 메모리아의 거점인 등대 내부. 기억을 먹는 몬스터들이 서식한다.',
    zoneCode: 'mist_sea_lighthouse',
    difficulty: 'normal',
    requiredLevel: 70,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_MS_005', count: 4 }, { monsterId: 'MON_MS_001', count: 3 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_MS_006', count: 5 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_MS_010', count: 3 }, { monsterId: 'MON_MS_004', count: 2 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_BOSS_MS01', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 8000, exp: 25000, items: [{ itemId: 'MAT_MEMORY_CORAL', rate: 0.5, count: 3 }, { itemId: 'MAT_LIGHTHOUSE_KEY', rate: 0.15, count: 1 }] },
    timeLimit: 900,
    entryCount: 3,
  },
  {
    code: 'dg_mistsea_lighthouse_h',
    name: '기억의 등대 (하드)',
    description: '레테의 잔영이 더 짙게 서린 등대. 기억 드레인 디버프에 주의.',
    zoneCode: 'mist_sea_lighthouse',
    difficulty: 'hard',
    requiredLevel: 75,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_MS_005', count: 6 }, { monsterId: 'MON_MS_010', count: 3 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_MS_006', count: 6 }, { monsterId: 'MON_MS_008', count: 2 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_MS_E04', count: 1 }, { monsterId: 'MON_MS_010', count: 4 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_MS_004', count: 6 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'MON_BOSS_MS01', count: 1 }, { monsterId: 'MON_MS_010', count: 2 }], isBoss: true },
    ],
    rewards: { gold: 16000, exp: 45000, items: [{ itemId: 'MAT_MEMORY_CORAL', rate: 0.6, count: 5 }, { itemId: 'MAT_LIGHTHOUSE_KEY', rate: 0.3, count: 1 }, { itemId: 'MAT_OBLIVION_ESSENCE', rate: 0.1, count: 1 }] },
    timeLimit: 1200,
    entryCount: 2,
  },
  {
    code: 'dg_mistsea_lighthouse_nm',
    name: '기억의 등대 (나이트메어)',
    description: '등대지기 메모리아의 완전한 기억이 폭주. 최상급 난이도.',
    zoneCode: 'mist_sea_lighthouse',
    difficulty: 'nightmare',
    requiredLevel: 82,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_MS_E04', count: 2 }, { monsterId: 'MON_MS_010', count: 5 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_MS_005', count: 8 }, { monsterId: 'MON_MS_008', count: 3 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_MS_E04', count: 2 }, { monsterId: 'MON_MS_E02', count: 1 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_MS_020', count: 4 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'MON_BOSS_MS01', count: 1 }, { monsterId: 'MON_MS_E04', count: 1 }, { monsterId: 'MON_MS_010', count: 3 }], isBoss: true },
    ],
    rewards: { gold: 25000, exp: 70000, items: [{ itemId: 'MAT_OBLIVION_ESSENCE', rate: 0.4, count: 2 }, { itemId: 'MAT_LIGHTHOUSE_KEY', rate: 0.5, count: 1 }, { itemId: 'EQUIP_LANTERN_MEMORIA', rate: 0.05, count: 1 }] },
    timeLimit: 1500,
    entryCount: 1,
  },
  // ── 2. 침몰 함대 묘지 (3난이도) ──
  {
    code: 'dg_mistsea_graveyard_n',
    name: '침몰 함대 묘지 (일반)',
    description: '안개해 바닥에 가라앉은 고대 함대의 잔해. 유령 선원과 해골 병사가 출몰.',
    zoneCode: 'mist_sea_graveyard',
    difficulty: 'normal',
    requiredLevel: 74,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_MS_016', count: 5 }, { monsterId: 'MON_MS_006', count: 3 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_MS_018', count: 2 }, { monsterId: 'MON_MS_016', count: 4 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_MS_E03', count: 1 }, { monsterId: 'MON_MS_006', count: 4 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_BOSS_MS02', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 10000, exp: 30000, items: [{ itemId: 'MAT_GHOST_ANCHOR', rate: 0.4, count: 2 }, { itemId: 'MAT_CAPTAIN_COMPASS', rate: 0.1, count: 1 }] },
    timeLimit: 900,
    entryCount: 3,
  },
  {
    code: 'dg_mistsea_graveyard_h',
    name: '침몰 함대 묘지 (하드)',
    description: '함장 레버넌트가 함대를 다시 지휘한다. 유령 함포에 주의.',
    zoneCode: 'mist_sea_graveyard',
    difficulty: 'hard',
    requiredLevel: 80,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_MS_016', count: 8 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_MS_006', count: 6 }, { monsterId: 'MON_MS_018', count: 3 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_MS_E03', count: 2 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_MS_016', count: 4 }, { monsterId: 'MON_MS_013', count: 3 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'MON_BOSS_MS02', count: 1 }, { monsterId: 'MON_MS_E03', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 18000, exp: 50000, items: [{ itemId: 'MAT_SUNKEN_TREASURE', rate: 0.4, count: 2 }, { itemId: 'EQUIP_SWORD_CAPTAIN', rate: 0.04, count: 1 }] },
    timeLimit: 1200,
    entryCount: 2,
  },
  {
    code: 'dg_mistsea_graveyard_nm',
    name: '침몰 함대 묘지 (나이트메어)',
    description: '고대 함대 전체가 깨어난다. 역대급 물량전.',
    zoneCode: 'mist_sea_graveyard',
    difficulty: 'nightmare',
    requiredLevel: 86,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_MS_016', count: 10 }, { monsterId: 'MON_MS_006', count: 5 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_MS_E03', count: 2 }, { monsterId: 'MON_MS_018', count: 4 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_MS_013', count: 6 }, { monsterId: 'MON_MS_E03', count: 1 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_MS_020', count: 3 }, { monsterId: 'MON_MS_E03', count: 2 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'MON_BOSS_MS02', count: 1 }, { monsterId: 'MON_MS_E03', count: 2 }, { monsterId: 'MON_MS_016', count: 4 }], isBoss: true },
    ],
    rewards: { gold: 28000, exp: 75000, items: [{ itemId: 'MAT_CAPTAIN_COMPASS', rate: 0.5, count: 1 }, { itemId: 'MAT_SUNKEN_TREASURE', rate: 0.6, count: 3 }, { itemId: 'EQUIP_SWORD_CAPTAIN', rate: 0.08, count: 1 }] },
    timeLimit: 1500,
    entryCount: 1,
  },
  // ── 3. 봉인 균열 회랑 (3난이도) ──
  {
    code: 'dg_mistsea_rift_n',
    name: '봉인 균열 회랑 (일반)',
    description: '봉인의 첨탑 하부에서 발견된 균열 회랑. 봉인 에너지와 레테의 힘이 충돌.',
    zoneCode: 'mist_sea_rift',
    difficulty: 'normal',
    requiredLevel: 78,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_MS_004', count: 5 }, { monsterId: 'MON_MS_008', count: 3 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_MS_012', count: 4 }, { monsterId: 'MON_MS_020', count: 2 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_MS_E05', count: 1 }, { monsterId: 'MON_MS_004', count: 4 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_BOSS_MS03', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 12000, exp: 35000, items: [{ itemId: 'MAT_SEAL_FRAGMENT', rate: 0.5, count: 3 }, { itemId: 'MAT_GUARDIAN_SEAL', rate: 0.1, count: 1 }] },
    timeLimit: 900,
    entryCount: 3,
  },
  {
    code: 'dg_mistsea_rift_h',
    name: '봉인 균열 회랑 (하드)',
    description: '균열이 확대되어 레테의 기운이 더 강해졌다.',
    zoneCode: 'mist_sea_rift',
    difficulty: 'hard',
    requiredLevel: 84,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_MS_012', count: 6 }, { monsterId: 'MON_MS_020', count: 3 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_MS_E05', count: 1 }, { monsterId: 'MON_MS_008', count: 4 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_MS_E02', count: 1 }, { monsterId: 'MON_MS_E05', count: 1 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_MS_004', count: 6 }, { monsterId: 'MON_MS_020', count: 3 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'MON_BOSS_MS03', count: 1 }, { monsterId: 'MON_MS_E05', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 20000, exp: 55000, items: [{ itemId: 'MAT_SEAL_FRAGMENT', rate: 0.6, count: 5 }, { itemId: 'EQUIP_SHIELD_GUARDIAN', rate: 0.04, count: 1 }] },
    timeLimit: 1200,
    entryCount: 2,
  },
  {
    code: 'dg_mistsea_rift_nm',
    name: '봉인 균열 회랑 (나이트메어)',
    description: '봉인이 거의 붕괴 직전. 가디언이 완전 폭주 상태.',
    zoneCode: 'mist_sea_rift',
    difficulty: 'nightmare',
    requiredLevel: 88,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_MS_E05', count: 2 }, { monsterId: 'MON_MS_020', count: 5 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_MS_012', count: 6 }, { monsterId: 'MON_MS_E02', count: 1 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_MS_E05', count: 2 }, { monsterId: 'MON_MS_E04', count: 1 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_MS_020', count: 6 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'MON_BOSS_MS03', count: 1 }, { monsterId: 'MON_MS_E05', count: 2 }, { monsterId: 'MON_MS_012', count: 3 }], isBoss: true },
    ],
    rewards: { gold: 30000, exp: 80000, items: [{ itemId: 'MAT_GUARDIAN_SEAL', rate: 0.5, count: 1 }, { itemId: 'MAT_SEAL_BREAKER', rate: 0.1, count: 1 }, { itemId: 'EQUIP_SHIELD_GUARDIAN', rate: 0.08, count: 1 }] },
    timeLimit: 1500,
    entryCount: 1,
  },
  // ── 4. 심해 소용돌이 (3난이도) ──
  {
    code: 'dg_mistsea_maelstrom_n',
    name: '심해 소용돌이 (일반)',
    description: '안개해 심층에 있는 거대 소용돌이. 수압과 해류가 몰아친다.',
    zoneCode: 'mist_sea_maelstrom',
    difficulty: 'normal',
    requiredLevel: 80,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_MS_003', count: 5 }, { monsterId: 'MON_MS_007', count: 3 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_MS_013', count: 4 }, { monsterId: 'MON_MS_011', count: 3 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_MS_E01', count: 1 }, { monsterId: 'MON_MS_007', count: 3 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_BOSS_MS04', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 14000, exp: 38000, items: [{ itemId: 'MAT_FROZEN_TENTACLE', rate: 0.5, count: 3 }, { itemId: 'MAT_TSUNAMI_HEART', rate: 0.1, count: 1 }] },
    timeLimit: 900,
    entryCount: 3,
  },
  {
    code: 'dg_mistsea_maelstrom_h',
    name: '심해 소용돌이 (하드)',
    description: '크라켄의 영역에 가까워졌다. 수압이 더 강해진다.',
    zoneCode: 'mist_sea_maelstrom',
    difficulty: 'hard',
    requiredLevel: 85,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_MS_007', count: 6 }, { monsterId: 'MON_MS_003', count: 4 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_MS_E01', count: 1 }, { monsterId: 'MON_MS_013', count: 5 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_MS_014', count: 4 }, { monsterId: 'MON_MS_E01', count: 1 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_MS_011', count: 5 }, { monsterId: 'MON_MS_007', count: 4 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'MON_BOSS_MS04', count: 1 }, { monsterId: 'MON_MS_E01', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 22000, exp: 58000, items: [{ itemId: 'MAT_FROZEN_PEARL', rate: 0.4, count: 2 }, { itemId: 'EQUIP_TRIDENT_TSUNAMI', rate: 0.03, count: 1 }] },
    timeLimit: 1200,
    entryCount: 2,
  },
  {
    code: 'dg_mistsea_maelstrom_nm',
    name: '심해 소용돌이 (나이트메어)',
    description: '대해마 츠나미가 전력을 다한다. 대해일 패턴을 완벽히 숙지해야 클리어 가능.',
    zoneCode: 'mist_sea_maelstrom',
    difficulty: 'nightmare',
    requiredLevel: 90,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_MS_E01', count: 2 }, { monsterId: 'MON_MS_007', count: 6 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_MS_013', count: 6 }, { monsterId: 'MON_MS_014', count: 4 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_MS_E01', count: 2 }, { monsterId: 'MON_MS_E03', count: 1 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_MS_020', count: 4 }, { monsterId: 'MON_MS_003', count: 5 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'MON_BOSS_MS04', count: 1 }, { monsterId: 'MON_MS_E01', count: 2 }, { monsterId: 'MON_MS_007', count: 3 }], isBoss: true },
    ],
    rewards: { gold: 32000, exp: 85000, items: [{ itemId: 'MAT_TSUNAMI_HEART', rate: 0.5, count: 1 }, { itemId: 'EQUIP_TRIDENT_TSUNAMI', rate: 0.06, count: 1 }] },
    timeLimit: 1500,
    entryCount: 1,
  },
  // ── 5. 봉인의 첨탑 최심부 (3난이도) ──
  {
    code: 'dg_mistsea_spire_n',
    name: '봉인의 첨탑 최심부 (일반)',
    description: '봉인의 첨탑 지하 — 레테의 분신이 잠든 최종 던전. 챕터 6 클리어 후 해금.',
    zoneCode: 'mist_sea_spire',
    difficulty: 'normal',
    requiredLevel: 85,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_MS_020', count: 5 }, { monsterId: 'MON_MS_010', count: 3 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_MS_E04', count: 1 }, { monsterId: 'MON_MS_E05', count: 1 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_MS_012', count: 4 }, { monsterId: 'MON_MS_008', count: 4 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_MS_E02', count: 1 }, { monsterId: 'MON_MS_020', count: 4 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'MON_BOSS_MS05', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 18000, exp: 45000, items: [{ itemId: 'MAT_LETHE_SHARD', rate: 0.3, count: 2 }, { itemId: 'MAT_LETHE_AVATAR_CORE', rate: 0.08, count: 1 }] },
    timeLimit: 1200,
    entryCount: 2,
  },
  {
    code: 'dg_mistsea_spire_h',
    name: '봉인의 첨탑 최심부 (하드)',
    description: '레테의 분신이 봉인을 더 깊이 잠식했다. 기억 파괴 스킬 권장.',
    zoneCode: 'mist_sea_spire',
    difficulty: 'hard',
    requiredLevel: 88,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_MS_020', count: 6 }, { monsterId: 'MON_MS_E04', count: 1 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_MS_E05', count: 2 }, { monsterId: 'MON_MS_010', count: 4 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_MS_E02', count: 1 }, { monsterId: 'MON_MS_E04', count: 1 }, { monsterId: 'MON_MS_020', count: 4 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_MS_012', count: 5 }, { monsterId: 'MON_MS_E05', count: 1 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'MON_BOSS_MS05', count: 1 }, { monsterId: 'MON_MS_E04', count: 1 }, { monsterId: 'MON_MS_020', count: 2 }], isBoss: true },
    ],
    rewards: { gold: 28000, exp: 70000, items: [{ itemId: 'MAT_OBLIVION_ESSENCE', rate: 0.5, count: 3 }, { itemId: 'EQUIP_SWORD_LETHE', rate: 0.03, count: 1 }] },
    timeLimit: 1500,
    entryCount: 1,
  },
  {
    code: 'dg_mistsea_spire_nm',
    name: '봉인의 첨탑 최심부 (나이트메어)',
    description: '레테 화신 형태의 분신과 직접 대결. 에테르나 크로니클 최고 난이도 던전.',
    zoneCode: 'mist_sea_spire',
    difficulty: 'nightmare',
    requiredLevel: 90,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_MS_E04', count: 2 }, { monsterId: 'MON_MS_E05', count: 2 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_MS_020', count: 8 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_MS_E02', count: 1 }, { monsterId: 'MON_MS_E04', count: 1 }, { monsterId: 'MON_MS_E05', count: 1 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_MS_010', count: 6 }, { monsterId: 'MON_MS_E05', count: 2 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'MON_BOSS_MS05', count: 1 }, { monsterId: 'MON_MS_E04', count: 2 }, { monsterId: 'MON_MS_020', count: 4 }], isBoss: true },
    ],
    rewards: { gold: 35000, exp: 100000, items: [{ itemId: 'MAT_LETHE_AVATAR_CORE', rate: 0.5, count: 1 }, { itemId: 'EQUIP_SWORD_LETHE', rate: 0.06, count: 1 }, { itemId: 'MAT_LETHE_SHARD', rate: 0.6, count: 5 }] },
    timeLimit: 1800,
    entryCount: 1,
  },

  // ═══ 기억의 심연 (Lv.70-80) [P11-19] ═══════════════════════════

  // ── 1. 침묵의 해구 ────────────────────────────────────────────
  {
    code: 'dg_silent_trench_n',
    name: '침묵의 해구 (일반)',
    description: '심연의 입구. 빛이 닿지 않는 해구에서 기억을 잃은 생물들이 배회한다.',
    zoneCode: 'memory_abyss_trench',
    difficulty: 'normal',
    requiredLevel: 70,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_abyss_angler', count: 4 }, { monsterId: 'mob_memory_eel', count: 2 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_void_crab', count: 3 }, { monsterId: 'mob_time_jellyfish', count: 3 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_forgotten_wraith', count: 4 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'boss_abyss_guardian', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 8000, exp: 25000, items: [{ itemId: 'item_abyss_scale', rate: 0.40, count: 3 }, { itemId: 'item_abyss_gem', rate: 0.10, count: 1 }] },
    timeLimit: 900,
    entryCount: 3,
  },
  {
    code: 'dg_silent_trench_h',
    name: '침묵의 해구 (하드)',
    description: '강화된 심연 생물들이 출몰한다. 산소 관리에 유의하라.',
    zoneCode: 'memory_abyss_trench',
    difficulty: 'hard',
    requiredLevel: 73,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_abyss_angler', count: 6 }, { monsterId: 'mob_memory_eel', count: 3 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_void_crab', count: 4 }, { monsterId: 'mob_coral_golem', count: 2 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_forgotten_wraith', count: 5 }, { monsterId: 'mob_pressure_serpent', count: 2 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'elite_leviathan_spawn', count: 1 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'boss_abyss_guardian', count: 1 }, { monsterId: 'mob_void_crab', count: 3 }], isBoss: true },
    ],
    rewards: { gold: 16000, exp: 50000, items: [{ itemId: 'item_abyss_gem', rate: 0.20, count: 1 }, { itemId: 'item_abyss_guardian_core', rate: 0.08, count: 1 }] },
    timeLimit: 1200,
    entryCount: 2,
  },
  {
    code: 'dg_silent_trench_nm',
    name: '침묵의 해구 (나이트메어)',
    description: '심연의 모든 공포가 해방된다. 최정예 파티만 도전하라.',
    zoneCode: 'memory_abyss_trench',
    difficulty: 'nightmare',
    requiredLevel: 76,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_abyss_angler', count: 8 }, { monsterId: 'mob_forgotten_wraith', count: 4 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_coral_golem', count: 3 }, { monsterId: 'mob_pressure_serpent', count: 3 }, { monsterId: 'mob_void_crab', count: 3 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'elite_leviathan_spawn', count: 1 }, { monsterId: 'elite_chrono_hydra', count: 1 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'mob_forgotten_wraith', count: 6 }, { monsterId: 'mob_abyssal_mimic', count: 2 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'boss_abyss_guardian', count: 1 }, { monsterId: 'elite_leviathan_spawn', count: 1 }, { monsterId: 'mob_void_crab', count: 4 }], isBoss: true },
    ],
    rewards: { gold: 28000, exp: 85000, items: [{ itemId: 'item_abyss_guardian_core', rate: 0.18, count: 1 }, { itemId: 'item_abyss_gem', rate: 0.35, count: 2 }] },
    timeLimit: 1500,
    entryCount: 1,
  },

  // ── 2. 시간 나선 회랑 ─────────────────────────────────────────
  {
    code: 'dg_chrono_spiral_n',
    name: '시간 나선 회랑 (일반)',
    description: '시간이 나선형으로 흐르는 회랑. 과거와 미래의 몬스터가 동시에 출현한다.',
    zoneCode: 'memory_abyss_spiral',
    difficulty: 'normal',
    requiredLevel: 72,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_time_jellyfish', count: 5 }, { monsterId: 'mob_chrono_barnacle', count: 3 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_warp_squid', count: 3 }, { monsterId: 'mob_temporal_polyp', count: 4 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_chrono_nautilus', count: 3 }, { monsterId: 'mob_drift_phantom', count: 2 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'boss_chrono_serpent', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 10000, exp: 30000, items: [{ itemId: 'item_chrono_shard', rate: 0.45, count: 3 }, { itemId: 'item_chrono_shell', rate: 0.15, count: 1 }] },
    timeLimit: 900,
    entryCount: 3,
  },
  {
    code: 'dg_chrono_spiral_h',
    name: '시간 나선 회랑 (하드)',
    description: '시간 왜곡이 심화된 회랑. 스킬 쿨다운이 무작위로 변한다.',
    zoneCode: 'memory_abyss_spiral',
    difficulty: 'hard',
    requiredLevel: 75,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_time_jellyfish', count: 6 }, { monsterId: 'mob_warp_squid', count: 3 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_chrono_nautilus', count: 4 }, { monsterId: 'mob_temporal_polyp', count: 3 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'elite_chrono_hydra', count: 1 }, { monsterId: 'mob_chrono_barnacle', count: 4 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'mob_drift_phantom', count: 4 }, { monsterId: 'mob_warp_squid', count: 3 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'boss_chrono_serpent', count: 1 }, { monsterId: 'mob_time_jellyfish', count: 4 }], isBoss: true },
    ],
    rewards: { gold: 20000, exp: 60000, items: [{ itemId: 'item_ouroboros_fang', rate: 0.10, count: 1 }, { itemId: 'item_chrono_shard', rate: 0.50, count: 5 }] },
    timeLimit: 1200,
    entryCount: 2,
  },
  {
    code: 'dg_chrono_spiral_nm',
    name: '시간 나선 회랑 (나이트메어)',
    description: '시간이 완전히 붕괴한 회랑. 우로보로스가 완전한 힘을 발휘한다.',
    zoneCode: 'memory_abyss_spiral',
    difficulty: 'nightmare',
    requiredLevel: 78,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_warp_squid', count: 5 }, { monsterId: 'mob_chrono_nautilus', count: 4 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'elite_chrono_hydra', count: 1 }, { monsterId: 'elite_temporal_lord', count: 1 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_drift_phantom', count: 6 }, { monsterId: 'mob_temporal_polyp', count: 4 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'mob_chrono_nautilus', count: 5 }, { monsterId: 'mob_abyssal_mimic', count: 2 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'boss_chrono_serpent', count: 1 }, { monsterId: 'elite_chrono_hydra', count: 1 }, { monsterId: 'mob_warp_squid', count: 3 }], isBoss: true },
    ],
    rewards: { gold: 32000, exp: 95000, items: [{ itemId: 'item_ouroboros_fang', rate: 0.20, count: 1 }, { itemId: 'item_chrono_shell', rate: 0.40, count: 3 }] },
    timeLimit: 1500,
    entryCount: 1,
  },

  // ── 3. 기억 산호 정원 ─────────────────────────────────────────
  {
    code: 'dg_memory_garden_n',
    name: '기억 산호 정원 (일반)',
    description: '기억이 결정화된 산호가 가득한 정원. 아름답지만 위험하다.',
    zoneCode: 'memory_abyss_garden',
    difficulty: 'normal',
    requiredLevel: 72,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_memory_leech', count: 5 }, { monsterId: 'mob_memory_starfish', count: 3 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_coral_golem', count: 2 }, { monsterId: 'mob_memory_eel', count: 3 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_echo_manta', count: 3 }, { monsterId: 'mob_void_anemone', count: 3 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'boss_memory_colossus', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 9000, exp: 28000, items: [{ itemId: 'item_memory_coral', rate: 0.40, count: 3 }, { itemId: 'item_memory_blood', rate: 0.30, count: 2 }] },
    timeLimit: 900,
    entryCount: 3,
  },
  {
    code: 'dg_memory_garden_h',
    name: '기억 산호 정원 (하드)',
    description: '기억 산호가 폭주하여 정원 전체가 기억 침식 상태이다.',
    zoneCode: 'memory_abyss_garden',
    difficulty: 'hard',
    requiredLevel: 75,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_memory_leech', count: 6 }, { monsterId: 'mob_echo_manta', count: 3 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_coral_golem', count: 3 }, { monsterId: 'mob_memory_starfish', count: 3 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'elite_memory_kraken', count: 1 }, { monsterId: 'mob_void_anemone', count: 3 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'mob_memory_eel', count: 5 }, { monsterId: 'mob_echo_manta', count: 3 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'boss_memory_colossus', count: 1 }, { monsterId: 'mob_coral_golem', count: 2 }], isBoss: true },
    ],
    rewards: { gold: 18000, exp: 55000, items: [{ itemId: 'item_colossus_memory', rate: 0.08, count: 1 }, { itemId: 'item_memory_coral', rate: 0.50, count: 5 }] },
    timeLimit: 1200,
    entryCount: 2,
  },
  {
    code: 'dg_memory_garden_nm',
    name: '기억 산호 정원 (나이트메어)',
    description: '대망각의 기억이 폭주한다. 기억의 거신이 완전 각성한다.',
    zoneCode: 'memory_abyss_garden',
    difficulty: 'nightmare',
    requiredLevel: 78,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_echo_manta', count: 5 }, { monsterId: 'mob_memory_leech', count: 6 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_coral_golem', count: 4 }, { monsterId: 'mob_memory_starfish', count: 4 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'elite_memory_kraken', count: 1 }, { monsterId: 'elite_void_whale', count: 1 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'mob_void_anemone', count: 5 }, { monsterId: 'mob_abyssal_mimic', count: 3 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'boss_memory_colossus', count: 1 }, { monsterId: 'elite_memory_kraken', count: 1 }, { monsterId: 'mob_coral_golem', count: 3 }], isBoss: true },
    ],
    rewards: { gold: 30000, exp: 90000, items: [{ itemId: 'item_colossus_memory', rate: 0.18, count: 1 }, { itemId: 'item_memory_coral', rate: 0.55, count: 6 }] },
    timeLimit: 1500,
    entryCount: 1,
  },

  // ── 4. 공허의 왕좌 ────────────────────────────────────────────
  {
    code: 'dg_void_throne_n',
    name: '공허의 왕좌 (일반)',
    description: '공허의 여제가 군림하는 심연의 궁전.',
    zoneCode: 'memory_abyss_throne',
    difficulty: 'normal',
    requiredLevel: 74,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_void_crab', count: 4 }, { monsterId: 'mob_void_anemone', count: 3 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_drift_phantom', count: 4 }, { monsterId: 'mob_forgotten_diver', count: 3 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_brine_elemental', count: 3 }, { monsterId: 'mob_abyssal_mimic', count: 2 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'boss_void_empress', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 12000, exp: 35000, items: [{ itemId: 'item_void_shell', rate: 0.40, count: 3 }, { itemId: 'item_void_petal', rate: 0.35, count: 2 }] },
    timeLimit: 1000,
    entryCount: 3,
  },
  {
    code: 'dg_void_throne_h',
    name: '공허의 왕좌 (하드)',
    description: '여제의 친위대가 해방된 공허의 궁전.',
    zoneCode: 'memory_abyss_throne',
    difficulty: 'hard',
    requiredLevel: 77,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_void_crab', count: 5 }, { monsterId: 'mob_drift_phantom', count: 4 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_forgotten_diver', count: 4 }, { monsterId: 'mob_brine_elemental', count: 3 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'elite_void_whale', count: 1 }, { monsterId: 'mob_void_anemone', count: 4 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'mob_abyssal_mimic', count: 3 }, { monsterId: 'mob_forgotten_wraith', count: 4 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'boss_void_empress', count: 1 }, { monsterId: 'mob_drift_phantom', count: 3 }], isBoss: true },
    ],
    rewards: { gold: 22000, exp: 65000, items: [{ itemId: 'item_void_empress_crown', rate: 0.06, count: 1 }, { itemId: 'item_void_ambergris', rate: 0.15, count: 1 }] },
    timeLimit: 1300,
    entryCount: 2,
  },
  {
    code: 'dg_void_throne_nm',
    name: '공허의 왕좌 (나이트메어)',
    description: '공허의 여제가 차원을 열어 최종 형태로 변신한다.',
    zoneCode: 'memory_abyss_throne',
    difficulty: 'nightmare',
    requiredLevel: 80,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_drift_phantom', count: 6 }, { monsterId: 'mob_void_crab', count: 5 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'elite_void_whale', count: 1 }, { monsterId: 'elite_temporal_lord', count: 1 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_abyssal_mimic', count: 4 }, { monsterId: 'mob_brine_elemental', count: 4 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'mob_forgotten_diver', count: 6 }, { monsterId: 'mob_forgotten_wraith', count: 4 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'boss_void_empress', count: 1 }, { monsterId: 'elite_void_whale', count: 1 }, { monsterId: 'mob_drift_phantom', count: 4 }], isBoss: true },
    ],
    rewards: { gold: 35000, exp: 100000, items: [{ itemId: 'item_void_empress_crown', rate: 0.15, count: 1 }, { itemId: 'item_void_ambergris', rate: 0.30, count: 2 }] },
    timeLimit: 1600,
    entryCount: 1,
  },

  // ── 5. 시조 레비아탄의 둥지 ───────────────────────────────────
  {
    code: 'dg_leviathan_nest_n',
    name: '시조 레비아탄의 둥지 (일반)',
    description: '기억의 심연 최심부. 원초의 괴수가 잠들어 있다.',
    zoneCode: 'memory_abyss_nest',
    difficulty: 'normal',
    requiredLevel: 76,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_abyss_angler', count: 5 }, { monsterId: 'mob_pressure_serpent', count: 3 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'mob_abyss_urchin', count: 4 }, { monsterId: 'mob_brine_elemental', count: 3 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'elite_leviathan_spawn', count: 2 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'boss_leviathan_prime', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 15000, exp: 40000, items: [{ itemId: 'item_leviathan_scale', rate: 0.30, count: 2 }, { itemId: 'item_leviathan_heart', rate: 0.03, count: 1 }] },
    timeLimit: 1200,
    entryCount: 2,
  },
  {
    code: 'dg_leviathan_nest_h',
    name: '시조 레비아탄의 둥지 (하드)',
    description: '레비아탄이 각성하기 시작했다. 아종들이 둥지를 수호한다.',
    zoneCode: 'memory_abyss_nest',
    difficulty: 'hard',
    requiredLevel: 78,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'mob_abyss_angler', count: 6 }, { monsterId: 'mob_abyss_urchin', count: 4 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'elite_leviathan_spawn', count: 2 }, { monsterId: 'mob_pressure_serpent', count: 3 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'elite_chrono_hydra', count: 1 }, { monsterId: 'elite_memory_kraken', count: 1 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'mob_forgotten_diver', count: 5 }, { monsterId: 'mob_abyssal_mimic', count: 3 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'boss_leviathan_prime', count: 1 }, { monsterId: 'elite_leviathan_spawn', count: 2 }], isBoss: true },
    ],
    rewards: { gold: 28000, exp: 80000, items: [{ itemId: 'item_leviathan_heart', rate: 0.08, count: 1 }, { itemId: 'item_leviathan_scale', rate: 0.45, count: 3 }] },
    timeLimit: 1500,
    entryCount: 1,
  },
  {
    code: 'dg_leviathan_nest_nm',
    name: '시조 레비아탄의 둥지 (나이트메어)',
    description: '시조 레비아탄이 완전 각성. 심연 전체가 진동한다. 최고 난이도 콘텐츠.',
    zoneCode: 'memory_abyss_nest',
    difficulty: 'nightmare',
    requiredLevel: 80,
    maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'elite_leviathan_spawn', count: 3 }, { monsterId: 'mob_abyss_angler', count: 6 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'elite_chrono_hydra', count: 1 }, { monsterId: 'elite_memory_kraken', count: 1 }, { monsterId: 'elite_void_whale', count: 1 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'mob_abyssal_mimic', count: 4 }, { monsterId: 'mob_forgotten_diver', count: 5 }, { monsterId: 'mob_abyss_urchin', count: 4 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'elite_temporal_lord', count: 1 }, { monsterId: 'elite_leviathan_spawn', count: 2 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'boss_leviathan_prime', count: 1 }, { monsterId: 'elite_leviathan_spawn', count: 2 }, { monsterId: 'mob_pressure_serpent', count: 4 }], isBoss: true },
    ],
    rewards: { gold: 40000, exp: 120000, items: [{ itemId: 'item_leviathan_heart', rate: 0.15, count: 1 }, { itemId: 'item_leviathan_scale', rate: 0.55, count: 5 }, { itemId: 'item_abyss_guardian_core', rate: 0.25, count: 1 }] },
    timeLimit: 1800,
    entryCount: 1,
  },

  // ═══ P14-19: 시간의 균열 던전 5개 × 3난이도 (Lv.85~100) ══════

  // --- 1. 시간의 회랑 (Corridor of Time) ---
  { code: 'dg_rift_chrono_n', name: '시간의 회랑 (일반)', description: '시간의 균열 입구에 형성된 왜곡된 통로. 시간 파편 몬스터들이 서식한다.', zoneCode: 'temporal_rift_zone_1', difficulty: 'normal', requiredLevel: 85, maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_TR_001', count: 6 }, { monsterId: 'MON_TR_002', count: 3 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_TR_003', count: 4 }, { monsterId: 'MON_TR_005', count: 4 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_TR_006', count: 3 }, { monsterId: 'MON_TR_004', count: 3 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_TR_BOSS_001', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 15000, exp: 35000, items: [{ itemId: 'MAT_TEMPORAL_SLIME', rate: 0.50, count: 3 }, { itemId: 'MAT_TIME_CRYSTAL', rate: 0.20, count: 1 }] }, timeLimit: 900, entryCount: 3 },
  { code: 'dg_rift_chrono_h', name: '시간의 회랑 (영웅)', description: '시간 왜곡이 심화된 회랑. 몬스터들이 시간 가속 버프를 받는다.', zoneCode: 'temporal_rift_zone_1', difficulty: 'hard', requiredLevel: 90, maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_TR_001', count: 8 }, { monsterId: 'MON_TR_006', count: 4 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_TR_008', count: 5 }, { monsterId: 'MON_TR_009', count: 4 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_TR_011', count: 4 }, { monsterId: 'MON_TR_ELITE_001', count: 1 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_TR_004', count: 6 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'MON_TR_BOSS_001', count: 1 }, { monsterId: 'MON_TR_002', count: 4 }], isBoss: true },
    ],
    rewards: { gold: 35000, exp: 75000, items: [{ itemId: 'MAT_TIME_CRYSTAL', rate: 0.40, count: 2 }, { itemId: 'EQUIP_AION_TIMEPIECE', rate: 0.05, count: 1 }] }, timeLimit: 1200, entryCount: 2 },
  { code: 'dg_rift_chrono_l', name: '시간의 회랑 (전설)', description: '시간이 완전히 정지된 회랑. 시간 정지 기믹을 해제하며 진행해야 한다.', zoneCode: 'temporal_rift_zone_1', difficulty: 'legendary', requiredLevel: 95, maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_TR_011', count: 6 }, { monsterId: 'MON_TR_013', count: 4 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_TR_016', count: 5 }, { monsterId: 'MON_TR_ELITE_001', count: 1 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_TR_018', count: 4 }, { monsterId: 'MON_TR_ELITE_005', count: 1 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_TR_014', count: 6 }, { monsterId: 'MON_TR_020', count: 4 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'MON_TR_BOSS_001', count: 1 }, { monsterId: 'MON_TR_ELITE_001', count: 2 }], isBoss: true },
    ],
    rewards: { gold: 60000, exp: 130000, items: [{ itemId: 'MAT_CHRONOS_ESSENCE', rate: 0.15, count: 1 }, { itemId: 'EQUIP_AION_TIMEPIECE', rate: 0.10, count: 1 }] }, timeLimit: 1500, entryCount: 1 },

  // --- 2. 패러독스 미궁 (Paradox Labyrinth) ---
  { code: 'dg_rift_paradox_n', name: '패러독스 미궁 (일반)', description: '인과율이 뒤틀린 미궁. 같은 방을 다시 방문하면 다른 적이 출현한다.', zoneCode: 'temporal_rift_zone_2', difficulty: 'normal', requiredLevel: 87, maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_TR_005', count: 6 }, { monsterId: 'MON_TR_007', count: 3 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_TR_008', count: 5 }, { monsterId: 'MON_TR_010', count: 3 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_TR_012', count: 5 }, { monsterId: 'MON_TR_003', count: 3 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_TR_BOSS_002', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 18000, exp: 40000, items: [{ itemId: 'MAT_PARADOX_WING', rate: 0.45, count: 3 }, { itemId: 'MAT_MOBIUS_STRIP', rate: 0.15, count: 1 }] }, timeLimit: 900, entryCount: 3 },
  { code: 'dg_rift_paradox_h', name: '패러독스 미궁 (영웅)', description: '미궁의 패러독스가 극대화. 보스가 시간을 되감아 전투를 반복시킨다.', zoneCode: 'temporal_rift_zone_2', difficulty: 'hard', requiredLevel: 92, maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_TR_012', count: 8 }, { monsterId: 'MON_TR_014', count: 3 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_TR_015', count: 5 }, { monsterId: 'MON_TR_017', count: 4 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_TR_ELITE_003', count: 1 }, { monsterId: 'MON_TR_010', count: 4 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_TR_019', count: 6 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'MON_TR_BOSS_002', count: 1 }, { monsterId: 'MON_TR_005', count: 4 }], isBoss: true },
    ],
    rewards: { gold: 40000, exp: 85000, items: [{ itemId: 'MAT_MOBIUS_STRIP', rate: 0.35, count: 2 }, { itemId: 'EQUIP_MOBIUS_RING', rate: 0.05, count: 1 }] }, timeLimit: 1200, entryCount: 2 },
  { code: 'dg_rift_paradox_l', name: '패러독스 미궁 (전설)', description: '시간의 무한 루프에 갇힌 미궁. 루프를 깨는 기믹을 해결해야 보스를 처치할 수 있다.', zoneCode: 'temporal_rift_zone_2', difficulty: 'legendary', requiredLevel: 97, maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_TR_017', count: 6 }, { monsterId: 'MON_TR_ELITE_003', count: 1 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_TR_014', count: 4 }, { monsterId: 'MON_TR_020', count: 4 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_TR_ELITE_004', count: 1 }, { monsterId: 'MON_TR_018', count: 4 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_TR_ELITE_002', count: 1 }, { monsterId: 'MON_TR_013', count: 5 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'MON_TR_BOSS_002', count: 1 }, { monsterId: 'MON_TR_ELITE_003', count: 1 }, { monsterId: 'MON_TR_ELITE_005', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 70000, exp: 140000, items: [{ itemId: 'EQUIP_MOBIUS_RING', rate: 0.10, count: 1 }, { itemId: 'MAT_CHRONOS_ESSENCE', rate: 0.20, count: 1 }] }, timeLimit: 1500, entryCount: 1 },

  // --- 3. 차원 파쇄 지대 (Dimension Fracture Zone) ---
  { code: 'dg_rift_collapse_n', name: '차원 파쇄 지대 (일반)', description: '차원이 부서지고 있는 위험 지역. 공간 왜곡 장애물을 피하며 진행해야 한다.', zoneCode: 'temporal_rift_zone_3', difficulty: 'normal', requiredLevel: 89, maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_TR_004', count: 5 }, { monsterId: 'MON_TR_007', count: 4 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_TR_010', count: 5 }, { monsterId: 'MON_TR_015', count: 3 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_TR_019', count: 6 }, { monsterId: 'MON_TR_012', count: 3 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_TR_BOSS_003', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 20000, exp: 45000, items: [{ itemId: 'MAT_DISTORTION_CORE', rate: 0.40, count: 2 }, { itemId: 'MAT_FRACTURE_SHARD', rate: 0.15, count: 1 }] }, timeLimit: 900, entryCount: 3 },
  { code: 'dg_rift_collapse_h', name: '차원 파쇄 지대 (영웅)', description: '붕괴 속도가 가속된 차원. 시간 제한이 더 엄격하며 분신 기믹이 추가된다.', zoneCode: 'temporal_rift_zone_3', difficulty: 'hard', requiredLevel: 93, maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_TR_015', count: 6 }, { monsterId: 'MON_TR_019', count: 4 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_TR_ELITE_002', count: 1 }, { monsterId: 'MON_TR_012', count: 5 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_TR_004', count: 4 }, { monsterId: 'MON_TR_010', count: 4 }, { monsterId: 'MON_TR_007', count: 3 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_TR_016', count: 5 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'MON_TR_BOSS_003', count: 1 }, { monsterId: 'MON_TR_007', count: 4 }], isBoss: true },
    ],
    rewards: { gold: 45000, exp: 90000, items: [{ itemId: 'MAT_FRACTURE_SHARD', rate: 0.35, count: 2 }, { itemId: 'EQUIP_FRACTURE_GAUNTLET', rate: 0.05, count: 1 }] }, timeLimit: 1100, entryCount: 2 },
  { code: 'dg_rift_collapse_l', name: '차원 파쇄 지대 (전설)', description: '차원 붕괴 직전의 임계 지역. 분신 3체 기믹이 동시 진행된다.', zoneCode: 'temporal_rift_zone_3', difficulty: 'legendary', requiredLevel: 98, maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_TR_ELITE_002', count: 1 }, { monsterId: 'MON_TR_ELITE_004', count: 1 }, { monsterId: 'MON_TR_015', count: 4 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_TR_020', count: 5 }, { monsterId: 'MON_TR_019', count: 5 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_TR_018', count: 4 }, { monsterId: 'MON_TR_016', count: 4 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_TR_ELITE_002', count: 2 }, { monsterId: 'MON_TR_004', count: 6 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'MON_TR_BOSS_003', count: 1 }, { monsterId: 'MON_TR_ELITE_002', count: 2 }], isBoss: true },
    ],
    rewards: { gold: 75000, exp: 150000, items: [{ itemId: 'EQUIP_FRACTURE_GAUNTLET', rate: 0.10, count: 1 }, { itemId: 'MAT_CHRONOS_ESSENCE', rate: 0.20, count: 1 }] }, timeLimit: 1500, entryCount: 1 },

  // --- 4. 크로노스의 시계탑 (Chronos Clocktower) ---
  { code: 'dg_rift_echo_n', name: '크로노스의 시계탑 (일반)', description: '시간의 신 크로노스가 남긴 시계탑. 층마다 시간 기믹이 다르다.', zoneCode: 'temporal_rift_zone_4', difficulty: 'normal', requiredLevel: 91, maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_TR_006', count: 5 }, { monsterId: 'MON_TR_009', count: 4 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_TR_013', count: 5 }, { monsterId: 'MON_TR_011', count: 3 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_TR_016', count: 4 }, { monsterId: 'MON_TR_018', count: 3 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_TR_BOSS_004', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 25000, exp: 50000, items: [{ itemId: 'MAT_CLOCKWORK_GEAR', rate: 0.50, count: 3 }, { itemId: 'MAT_CHRONOS_ESSENCE', rate: 0.10, count: 1 }] }, timeLimit: 1000, entryCount: 3 },
  { code: 'dg_rift_echo_h', name: '크로노스의 시계탑 (영웅)', description: '시계탑의 시간이 폭주. 전체 회복 기믹을 타이밍에 맞춰 차단해야 한다.', zoneCode: 'temporal_rift_zone_4', difficulty: 'hard', requiredLevel: 95, maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_TR_013', count: 6 }, { monsterId: 'MON_TR_018', count: 4 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_TR_ELITE_005', count: 1 }, { monsterId: 'MON_TR_016', count: 4 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_TR_020', count: 5 }, { monsterId: 'MON_TR_011', count: 4 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_TR_ELITE_001', count: 1 }, { monsterId: 'MON_TR_009', count: 5 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'MON_TR_BOSS_004', count: 1 }, { monsterId: 'MON_TR_006', count: 4 }], isBoss: true },
    ],
    rewards: { gold: 50000, exp: 100000, items: [{ itemId: 'EQUIP_CHRONOS_FRAGMENT', rate: 0.05, count: 1 }, { itemId: 'MAT_CHRONOS_ESSENCE', rate: 0.25, count: 1 }] }, timeLimit: 1300, entryCount: 2 },
  { code: 'dg_rift_echo_l', name: '크로노스의 시계탑 (전설)', description: '시계탑 정상. 크로노스의 분신이 "종말의 시계" 전멸기를 시전한다. 기믹 실패 = 전멸.', zoneCode: 'temporal_rift_zone_4', difficulty: 'legendary', requiredLevel: 99, maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_TR_ELITE_001', count: 1 }, { monsterId: 'MON_TR_ELITE_005', count: 1 }, { monsterId: 'MON_TR_020', count: 4 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_TR_018', count: 5 }, { monsterId: 'MON_TR_014', count: 4 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_TR_ELITE_003', count: 1 }, { monsterId: 'MON_TR_ELITE_004', count: 1 }, { monsterId: 'MON_TR_013', count: 4 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_TR_016', count: 6 }, { monsterId: 'MON_TR_011', count: 4 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'MON_TR_BOSS_004', count: 1 }, { monsterId: 'MON_TR_ELITE_001', count: 1 }, { monsterId: 'MON_TR_ELITE_005', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 80000, exp: 160000, items: [{ itemId: 'EQUIP_CHRONOS_FRAGMENT', rate: 0.12, count: 1 }, { itemId: 'MAT_TEMPOVORE_FANG', rate: 0.15, count: 1 }] }, timeLimit: 1500, entryCount: 1 },

  // --- 5. 시간 포식자의 둥지 (Tempovore's Nest) — 최종 던전 ---
  { code: 'dg_rift_origin_n', name: '시간 포식자의 둥지 (일반)', description: '시간의 균열 최심부. 시간 포식자 템포보어가 서식하는 끝의 공간.', zoneCode: 'temporal_rift_zone_5', difficulty: 'normal', requiredLevel: 93, maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_TR_020', count: 6 }, { monsterId: 'MON_TR_019', count: 4 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_TR_ELITE_004', count: 1 }, { monsterId: 'MON_TR_015', count: 4 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_TR_017', count: 5 }, { monsterId: 'MON_TR_014', count: 4 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_TR_BOSS_005', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 30000, exp: 60000, items: [{ itemId: 'MAT_TEMPOVORE_FANG', rate: 0.25, count: 1 }, { itemId: 'MAT_DEVOURER_LARVA', rate: 0.40, count: 2 }] }, timeLimit: 1200, entryCount: 3 },
  { code: 'dg_rift_origin_h', name: '시간 포식자의 둥지 (영웅)', description: '둥지 심층. 템포보어가 "존재 소거" 페이즈를 시전한다.', zoneCode: 'temporal_rift_zone_5', difficulty: 'hard', requiredLevel: 97, maxPlayers: 4,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_TR_020', count: 8 }, { monsterId: 'MON_TR_ELITE_004', count: 1 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_TR_ELITE_002', count: 1 }, { monsterId: 'MON_TR_ELITE_003', count: 1 }, { monsterId: 'MON_TR_014', count: 4 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_TR_018', count: 5 }, { monsterId: 'MON_TR_016', count: 4 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_TR_ELITE_005', count: 1 }, { monsterId: 'MON_TR_017', count: 5 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'MON_TR_BOSS_005', count: 1 }, { monsterId: 'MON_TR_020', count: 4 }], isBoss: true },
    ],
    rewards: { gold: 60000, exp: 120000, items: [{ itemId: 'EQUIP_TEMPOVORE_HEART', rate: 0.05, count: 1 }, { itemId: 'MAT_CHRONOS_ESSENCE', rate: 0.30, count: 1 }] }, timeLimit: 1500, entryCount: 2 },
  { code: 'dg_rift_origin_l', name: '시간 포식자의 둥지 (전설)', description: '시간의 끝. 템포보어 최종 형태와의 결전. 8인 레이드 권장. 전멸기 "존재 소거"를 3회 견뎌야 한다.', zoneCode: 'temporal_rift_zone_5', difficulty: 'legendary', requiredLevel: 100, maxPlayers: 8,
    waves: [
      { wave: 1, monsters: [{ monsterId: 'MON_TR_ELITE_001', count: 1 }, { monsterId: 'MON_TR_ELITE_002', count: 1 }, { monsterId: 'MON_TR_020', count: 6 }], isBoss: false },
      { wave: 2, monsters: [{ monsterId: 'MON_TR_ELITE_003', count: 1 }, { monsterId: 'MON_TR_ELITE_004', count: 1 }, { monsterId: 'MON_TR_018', count: 6 }], isBoss: false },
      { wave: 3, monsters: [{ monsterId: 'MON_TR_ELITE_005', count: 2 }, { monsterId: 'MON_TR_014', count: 4 }, { monsterId: 'MON_TR_016', count: 4 }], isBoss: false },
      { wave: 4, monsters: [{ monsterId: 'MON_TR_BOSS_003', count: 1 }, { monsterId: 'MON_TR_BOSS_004', count: 1 }], isBoss: false },
      { wave: 5, monsters: [{ monsterId: 'MON_TR_BOSS_005', count: 1 }], isBoss: true },
    ],
    rewards: { gold: 100000, exp: 200000, items: [{ itemId: 'EQUIP_TEMPOVORE_HEART', rate: 0.12, count: 1 }, { itemId: 'MAT_CHRONOS_ESSENCE', rate: 0.40, count: 2 }, { itemId: 'EQUIP_CHRONOS_FRAGMENT', rate: 0.08, count: 1 }] }, timeLimit: 1800, entryCount: 1 },
];

// ─── 시드 함수 ──────────────────────────────────────────────────

export async function seedDungeons(): Promise<void> {
  console.log('[Seed] 던전 시드 시작...');

  // 존 코드 → id 매핑 (zoneSeeds 에서 생성된 Zone 참조)
  const zones = await prisma.zone.findMany({ select: { id: true, code: true } });
  const zoneMap = new Map(zones.map((z) => [z.code, z.id]));

  let created = 0;
  for (const seed of DUNGEON_SEEDS) {
    const existing = await prisma.dungeon.findUnique({ where: { code: seed.code } });
    if (existing) continue;

    const zoneId = zoneMap.get(seed.zoneCode) ?? 'unknown';

    await prisma.dungeon.create({
      data: {
        code: seed.code,
        name: seed.name,
        description: seed.description,
        zoneId,
        difficulty: seed.difficulty,
        requiredLevel: seed.requiredLevel,
        maxPlayers: seed.maxPlayers,
        waves: seed.waves,
        rewards: seed.rewards,
        timeLimit: seed.timeLimit,
        entryCount: seed.entryCount,
      },
    });
    created++;
  }

  console.log(`[Seed] 던전 시드 완료 — ${created}개 생성 (총 ${DUNGEON_SEEDS.length}개 정의)`);
}
